services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: 
      - .env

  backend:
    build: .
    container_name: library_api
    command: >
      sh -c "
      python3 manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    restart : always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

  worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info -B
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
      - postgres
    env_file:
      - .env

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    env_file:
      - .env

  test:
    build: .
    container_name: test_container
    command: pytest
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 
    env_file:
      - .env

  rabbitmq_listener:
    build: .
    container_name: rabbitmq_listener
    restart: always
    command: python3 /app/rabbitmq/listener.py
    volumes:
      - ./core:/app
    depends_on:
      - rabbitmq
    env_file:
      - .env


volumes:
  static_volume:
  media_volume:
  postgres_data:
  smtp4dev-data:
