# Generated by Django 4.2.14 on 2024-07-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='writed_books',
        ),
    ]
