# Generated by Django 4.2.14 on 2024-07-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitList',
        ),
    ]
