# Generated by Django 4.2.14 on 2024-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_checkout_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
